#config-client微服务的远程配置文件
server:
  port: 8589
#spring:
#  application:
#    #此处需要严格注意，spring.application.name是微服务名称.而eureka中配置的instance-appname则是在此处没有配置的时候才生效，而instance-id则仅仅是在eureka上后面所显示的实例名称
#    name: order-api-feign
#此配置是开启所有的监控,在这个项目中，所需要测试的是豪猪监控面板，用到的是hystrix.stream，其实只需要配置一个就可以，这儿可以用逗号来分割开配置多个监控页面
#需要注意的是，在spring 2.0版本之后，web监控访问页面是默认关闭的，需要手动开启，默认只开启了info，另外还需要注意，此处的*号必须用前后单引号引起来，否则无效，其他单独配置可以不引
management:
  endpoints:
    web:
      exposure:
        include: '*'